### PR TITLE
sync all unsynced orders regardless of age

### LINKED ISSUE #8: Order sync doesn't work properly if new services exceed pagination before cron runs
The plugin uses the following code to generate a list of services to run against when syncing orders:

`$services = $this->Services->getList();`

The problem being that the service list generated by this follows Blesta's pagination rules so it is entirely possible that services which need to be synced will have already rolled over to page 2 or beyond by the time the cron runs.

Getting a full list of services and not using pagination would not be a good solution as it would be inefficient and setting a higher arbitrary number of services isn't exactly a good solution either.

I'm going to see if I can come up with a creative solution but worst case arbitrarily raising the number of services it runs against may be the best thing.

### PR DESCRIPTION
**Pull request by neonardo1**
fixes #8

### CODE REVIEW

File: thesslstore_plugin.php [hunk 1]
```diff
@@ -198,10 +198,18 @@ private function order_synchronization(){
 
         $order_query_resp = $api->order_query($order_query_request);
 
-        $services = $this->Services->getList();
+       $sub_query_sql = "SELECT `service_id` FROM `service_fields` WHERE `key` = 'thesslstore_fqdn' GROUP BY `service_id`";
```
Comment (tysonphillips) [inline thesslstore_plugin.php]: It'd be great if you could use the Record component to generate this query rather than writing it yourself. See [Record subqueries](https://github.com/phillipsdata/minphp-record#subqueries)

File: thesslstore_plugin.php [hunk 2]
```diff
@@ -198,10 +198,18 @@ private function order_synchronization(){
...
+
+       $services = $this->Record->select()->from("services")
+           ->leftJoin("service_fields", "services.id", "=", "service_fields.service_id", false)
+           ->where("service_fields.key", "=", "thesslstore_order_id")
+           ->where("services.status", "=", "active")
+           ->where("services.id", "notin", array($sub_query_sql), false)
+           ->fetchAll();
```
Comment (tysonphillips) [inline thesslstore_plugin.php]: This looks like it can load a lot of data into memory, so it'd be better to fetch and iterate over the PDOStatement object. You can clone the Record object to query with another instance, e.g.:

```
$record = clone $this->Record;
$services = $record->select(['id', 'date_renews'])->from('services')->...->getStatement();

foreach ($services as $service) {
    ...
}
unset($record);
```

File: thesslstore_plugin.php [hunk 3]
```diff
@@ -371,5 +379,4 @@ private function serviceFieldsToObject(array $fields) {
 
         return $data;
     }
-}
-?>
+}
```
Comment (tysonphillips) [inline thesslstore_plugin.php]: It's good to remove the unnecessary closing php tag, but there should exist a blank new line at the end of the file.

File: thesslstore_plugin.php (hunk 1 above)
Comment (neonardo1) [reply thesslstore_plugin.php]: updated in additional commits

File: thesslstore_plugin.php (hunk 2 above)
Comment (neonardo1) [reply thesslstore_plugin.php]: updated in latest commits

File: thesslstore_plugin.php (hunk 3 above)
Comment (neonardo1) [reply thesslstore_plugin.php]: good catch
